# -*- coding: utf-8 -*-
"""DL_점수계산.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJld9HZzWnq24NopCnmm3aabFYdMiqPX
"""

# 코랩 환경: 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

import os
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

# Constants
IMG_WIDTH = 1280
IMG_HEIGHT = 1280
IMG_AREA = IMG_WIDTH * IMG_HEIGHT

# Helper: 객체 필터링
def get_objects(bboxes, label):
    return [b for b in bboxes if b['label'] == label]

# Helper: 면적 계산
def area(obj):
    return obj['w'] * obj['h']

def calc_scores(data):
    if isinstance(data, list):
      data = data[0]

    # annotations와 bbox 키가 모두 존재하는지 확인
    if not isinstance(data, dict) or 'annotations' not in data or 'bbox' not in data['annotations']:
        return 0, 0, 0, 0  # 에러 방지용 기본값

    bboxes = data['annotations']['bbox']

    IMG_WIDTH, IMG_HEIGHT = 1280, 1280
    IMG_AREA = IMG_WIDTH * IMG_HEIGHT

    def get_objects(label):
        return [b for b in bboxes if b['label'] == label]

    def area(obj):
        return obj['w'] * obj['h']

    # ===== Openness (수정됨) =====
    #평가 요소: 문, 창문, 울타리, 길(요소 개수는 수정 없음, 점수 계산 지표 수정)

    openness = 0
    house = get_objects('집전체')[0]
    house_area = area(house)

    # 1. 문
    # 최대 70점, 존재하면 기본 50점
    # 문/집 면적 비율
    # 2% 미만: 작으면 작을수록 최대 -20점까지 감소되도록
    # 4% 이상: 크면 클수록 최대 +20점까지 증가되도록

    door_objs = get_objects('문')
    if door_objs:
        door = door_objs[0]
        door_ratio = area(door) / house_area
        door_score = 30
        if door_ratio < 0.02:
            door_score -= (0.02 - door_ratio) / 0.02 * 20  # 최대 -20
        elif door_ratio > 0.04:
            door_score += (door_ratio - 0.04) / 0.04 * 20  # 최대 +20
        door_score = min(50, max(30, door_score))  # 총합 최대 70
        openness += door_score

    # 2. 창문
    # 최대 50점, 창문 개수당 +10점
    # 창문/집 면적 비율
    # 0.5% 이하일 경우 최소 -2점까지 비율에 따라 마이너스
    # 1.5% 이상부터는 최대 2점까지 비율에 따라 플러스

    windows = get_objects('창문')
    window_score = min(len(windows), 5) * 10  # 개당 10점, 최대 50점

    for w in windows:
        ratio = area(w) / house_area
        if ratio <= 0.005:
            window_score -= 2 * (0.005 - ratio) / 0.005  # 최대 -2
        elif ratio >= 0.015:
            window_score += 2 * (ratio - 0.015) / 0.015  # 최대 +2
    window_score = min(30, max(0, window_score))
    openness += window_score

    # 3. 울타리
    # 최대 -50점, 존재하면 기본 -30점
    # 울타리의 높이가 집의 절반 이상일 경우 높이 비율에 따라 최대 -20점까지 감소

    fence_objs = get_objects('울타리')
    if fence_objs:
        fence = fence_objs[0]
        fence_score = -10
        height_ratio = fence['h'] / house['h']
        if height_ratio >= 0.5:
            extra_penalty = min(10, (height_ratio - 0.5) / 0.5 * 20)
            fence_score -= extra_penalty
        openness += fence_score

    # 4. 길
    # 존재할 경우 +30점

    if get_objects('길'):
        openness += 20

    openness = min(100, max(0, openness))


    # ===== Vitality (수정됨) =====
    # 🌞 태양 위치 점수 (최대 70점)
    sun_bbox = next((box for box in bboxes if box.get("label") == "태양"), None)
    if sun_bbox:
        center_x = sun_bbox["x"] + sun_bbox["w"] / 2
        center_y = sun_bbox["y"] + sun_bbox["h"] / 2
        center_score = 1 - abs(center_x - IMG_WIDTH / 2) / (IMG_WIDTH / 2)
        top_score = 1 - center_y / IMG_HEIGHT
        sun_score = ((center_score + top_score) / 2) * 50  # ✅ 70점 → 40점
    else:
        sun_score = 0

    # 🌿 자연물 개수 점수 (최대 35점)
    natural_labels = {"나무", "꽃", "잔디", "연못"}
    nature_count = sum(1 for box in bboxes if box.get("label") in natural_labels)
    nature_score = min(nature_count * 5, 35)  # ✅ 최대 35점

    # 🧭 객체 분산도 점수 (최대 25점)
    distributed_labels = {
        "집전체", "문", "창문", "울타리", "길",
        "태양", "굴뚝", "지붕", "연기",
        "나무", "꽃", "잔디", "연못"
    }

    centers = []
    for box in bboxes:
        if box.get("label") in distributed_labels:
            cx = box["x"] + box["w"] / 2
            cy = box["y"] + box["h"] / 2
            centers.append((cx, cy))

    if len(centers) >= 2:
        xs, ys = zip(*centers)
        std_x = np.std(xs) / IMG_WIDTH
        std_y = np.std(ys) / IMG_HEIGHT
        spread_score = ((std_x + std_y) / 2) * 50  # 0~1 범위 → 25점 스케일
        spread_score = min(spread_score, 25)
    else:
        spread_score = 0

    # 최종 vitality 점수
    vitality = min(100, round(sun_score + nature_score + spread_score, 2))



    # ===== Warmth (수정됨) =====
    # 평가 요소: 굴뚝 크기 비율, 태양 크기 비율, 꽃 개수
    chimney_objs = get_objects('굴뚝')
    chimney_area = area(chimney_objs[0]) if chimney_objs else 0
    chimney_ratio = chimney_area / house_area if house_area > 0 else 0
    chimney_score = min(30, chimney_ratio * 200)

    sun_area = area(sun_bbox) if sun_bbox else 0
    sun_ratio = sun_area / IMG_AREA
    sun_score = min(70, sun_ratio * 400)

    # 🌸 꽃 개수 기반 점수 (최대 30점)
    flower_objs = get_objects('꽃')
    flower_score = min(len(flower_objs) * 5, 30)

    warmth = min(100, chimney_score + sun_score + flower_score)



    # ===== Stability (수정됨) =====
    # 요소 비중: 지붕(50), 중심위치(30), 연기(20)
    roof = get_objects('지붕')[0]
    roof_ratio = area(roof) / house_area
    if 0.4 <= roof_ratio <= 0.6:
        roof_score_raw = 40
    elif roof_ratio < 0.4:
        roof_score_raw = max(0, 40 - ((0.4 - roof_ratio) / 0.4) * 40)
    else:
        roof_score_raw = max(0, 40 - ((roof_ratio - 0.6) / 0.4) * 40)

    # 지붕 점수: 40점 만점 → 50점 만점으로 환산
    roof_score = roof_score_raw * (50 / 40)

    # 중심 위치 점수 (30점 유지)
    house_cx = house['x'] + house['w'] / 2
    house_cy = house['y'] + house['h'] / 2
    dist = np.sqrt((house_cx - IMG_WIDTH / 2) ** 2 + (house_cy - IMG_HEIGHT / 2) ** 2)
    norm_dist = dist / np.sqrt((IMG_WIDTH / 2) ** 2 + (IMG_HEIGHT / 2) ** 2)
    center_score = max(0, 30 * (1 - norm_dist))

    # 연기 점수: 30점 만점 → 20점 만점으로 환산
    smoke_objs = get_objects('연기')
    if smoke_objs:
        smoke_ratio = area(smoke_objs[0]) / IMG_AREA
        raw_smoke_score = 0 if smoke_ratio > 0.05 else max(0, 30 * (1 - smoke_ratio / 0.05))
        smoke_score = raw_smoke_score * (20 / 30)
    else:
        smoke_score = 0

    # ✅ 좌우 치우침 감점: 최대 -15점
    x_offset = abs(house_cx - IMG_WIDTH / 2)  # 중심에서 얼마나 벗어났는지
    max_offset = IMG_WIDTH / 2  # 640
    shift_penalty = min(15, (x_offset / max_offset) * 15)  # 선형 감소 최대 -15점

    stability = round(min(100, roof_score + center_score + smoke_score - shift_penalty), 2)





    return openness, vitality, warmth, stability

results = []
json_dir = '/content/drive/MyDrive/TL_집'  # 실제 경로로 수정


for file in tqdm(os.listdir(json_dir)):
    if file.endswith('.json'):
        with open(os.path.join(json_dir, file), 'r', encoding='utf-8') as f:
            data = json.load(f)
            o, v, w, s = calc_scores(data)
            results.append({
                "filename": file,
                "Openness": o,
                "Vitality": v,
                "Warmth": w,
                "Structural_Stability": s
            })

df = pd.DataFrame(results)
df.to_csv('/content/drive/MyDrive/TL_score_result.csv', index=False)

df.info()

df.head()

import seaborn as sns

plt.figure(figsize=(16, 10))
cols = ['Openness', 'Vitality', 'Warmth', 'Structural_Stability']

for i, col in enumerate(cols):
    plt.subplot(2, 2, i + 1)
    sns.histplot(df[col], bins=20, kde=False, color='cornflowerblue', edgecolor='black')
    plt.title(f'{col} score')
    plt.xlabel('score')
    plt.ylabel('frequency')
    plt.xlim(0, 100)

plt.tight_layout()
plt.show()

# 각 지표별 최저 점수 출력
min_scores = df[['Openness', 'Vitality', 'Warmth', 'Structural_Stability']].min()
print("각 지표별 최저 점수:")
print(min_scores)